
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author silas
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        
        super("Funcionario");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        matriculaTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dataAdmissaoTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        salarioBaseTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        horaExtraTextField = new javax.swing.JTextField();
        valorHoraExtraTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        funCLTButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cnpjTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        valorContratoTextField = new javax.swing.JTextField();
        funcCLTRadioButton = new javax.swing.JRadioButton();
        funcPJRadioButton = new javax.swing.JRadioButton();
        funcPJButton = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Matricula:");

        jLabel3.setText("Data de Admissao:");

        jLabel4.setText("Salario Base:");

        jLabel5.setText("Hora Extra:");

        jLabel6.setText("Hora Extra (valor):");

        funCLTButton.setText("CLT");
        funCLTButton.setEnabled(false);
        funCLTButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funCLTButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("CNPJ:");

        cnpjTextField.setEnabled(false);

        jLabel9.setText("Valor Contrato:");

        valorContratoTextField.setEnabled(false);

        buttonGroup1.add(funcCLTRadioButton);
        funcCLTRadioButton.setText("Funcionario CLT");
        funcCLTRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcCLTRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(funcPJRadioButton);
        funcPJRadioButton.setText("Funcionario PJ");
        funcPJRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcPJRadioButtonActionPerformed(evt);
            }
        });

        funcPJButton.setText("PJ");
        funcPJButton.setEnabled(false);
        funcPJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funcPJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(horaExtraTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nomeTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel2)
                                        .addComponent(matriculaTextField)
                                        .addComponent(valorHoraExtraTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(valorContratoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8)
                                    .addComponent(cnpjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dataAdmissaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(salarioBaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(funcPJRadioButton)
                                    .addComponent(funcCLTRadioButton))
                                .addGap(51, 51, 51))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(funCLTButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(funcPJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(matriculaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataAdmissaoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salarioBaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(horaExtraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorHoraExtraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(funcCLTRadioButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(valorContratoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cnpjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(funcPJRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funCLTButton)
                    .addComponent(funcPJButton))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void funCLTButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funCLTButtonActionPerformed

        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
        FuncionarioCLT funCLT = new FuncionarioCLT("", "", 0.0);
        
        funCLT.setNome(nomeTextField.getText());
        funCLT.setMatricula(matriculaTextField.getText());
        funCLT.setDataAdmissao(LocalDate.parse(dataAdmissaoTextField.getText(), formato));
        funCLT.setSalarioBase(Double.parseDouble(salarioBaseTextField.getText()));
        funCLT.setHoraExtra(Integer.parseInt(salarioBaseTextField.getText()));
        
        JOptionPane.showMessageDialog(null, funCLT.getInfoGeral()+"\nBeneficio:\n"+funCLT.getBeneficios());
        
    }//GEN-LAST:event_funCLTButtonActionPerformed

    private void funcCLTRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcCLTRadioButtonActionPerformed

        funCLTButton.setEnabled(true);
        funcPJButton.setEnabled(false);
        valorContratoTextField.setEnabled(false);
        cnpjTextField.setEnabled(false);
        salarioBaseTextField.setEnabled(true); 
        salarioBaseTextField.setText("");

        
    }//GEN-LAST:event_funcCLTRadioButtonActionPerformed

    private void funcPJRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcPJRadioButtonActionPerformed
        funCLTButton.setEnabled(false);
        funcPJButton.setEnabled(true);
        valorContratoTextField.setEnabled(true);
        cnpjTextField.setEnabled(true);
        salarioBaseTextField.setText("0");
        salarioBaseTextField.setEnabled(false);
    }//GEN-LAST:event_funcPJRadioButtonActionPerformed

    private void funcPJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funcPJButtonActionPerformed

        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
        FuncionarioPJ funcPJ = new FuncionarioPJ("", "", "", 0.0);
        
        funcPJ.setNome(nomeTextField.getText());
        funcPJ.setMatricula(matriculaTextField.getText());
        funcPJ.setDataAdmissao(LocalDate.parse(dataAdmissaoTextField.getText(), formato));
        funcPJ.setCnpj(cnpjTextField.getText());
        funcPJ.setValorContrato(Double.parseDouble(valorContratoTextField.getText()));
        
        JOptionPane.showMessageDialog(null, funcPJ.getInfoGeral()+"\nBeneficios:\n"+funcPJ.getBeneficios());

    }//GEN-LAST:event_funcPJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cnpjTextField;
    private javax.swing.JTextField dataAdmissaoTextField;
    private javax.swing.JButton funCLTButton;
    private javax.swing.JRadioButton funcCLTRadioButton;
    private javax.swing.JButton funcPJButton;
    private javax.swing.JRadioButton funcPJRadioButton;
    private javax.swing.JTextField horaExtraTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField matriculaTextField;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JTextField salarioBaseTextField;
    private javax.swing.JTextField valorContratoTextField;
    private javax.swing.JTextField valorHoraExtraTextField;
    // End of variables declaration//GEN-END:variables
}
